### ISSUE TITLE
კომუნიკაციის სისტემის დახვეწა

### ISSUE THREAD

**Issue by otarza** [bitcamp-ge/bitcamp-platform#5]
ეს ზოგადი ტასკია რომელიც უფრო გრანულარულ ტასკებადაც შეიძლება დავშალოთ. 

ამ ტასკის მთავარი მიზანია - მენეჯერებსა და მომხმარებლებს შორის უკეთესი კომუნიკაციის მექანიზმის აწყობა ჩვენი პლათფორმის გავლით.

- [x] [SendGrid - ის ინტეგრაცია - Mail სერვერი](https://github.com/bitcamp-ge/bitcamp-platform/issues/6)
- [x] [კომენტარების thread - ის ვიზაულური გასუფთავება](https://github.com/bitcamp-ge/bitcamp-platform/issues/9);
- [x] [Full pager - ის ჩართვა მომხმარებლების სიაზე](https://github.com/bitcamp-ge/bitcamp-platform/issues/8)
- [x] ["ხარვეზის" - Boolean ველის დამატება პირველი ეტაპის პროფაილზე](https://github.com/bitcamp-ge/bitcamp-platform/issues/7)
- [x] [სორტირების ფუნქციონალი პირველი ეტაპის მომხმარებლების სიაზე](https://github.com/bitcamp-ge/bitcamp-platform/issues/3)
- [x] [სწრაფი ძებნა პირველი ეტაპის მომხმარებლების სიაში](https://github.com/bitcamp-ge/bitcamp-platform/issues/2)

**Comment by IliaNoz** [comment]
გამარჯობა, მზად ვარ ამ ტასკზე სამუშაოდ.

**Comment by otarza** [comment]
@IliaNoz გამარჯობა ილია, მადლობა დაინტერესებისთვის, შეგიძლია დაიწყო. კითხვები თუ გექნება Slack - ში ან აქვე შეგიძლია გამოუშვა კომენტარების სახით.

**Comment by otarza** [comment]
@IliaNoz - #25 - ი დამერჯილია რაც ნიშნავს რომ ეს ტასკი დასრულებულია.

შენი ანგარიშის ნომერი გამომიგზავნე ელ.ფოსტაზე oto.zakalashvili@gmail.om - Subject - ში მიუთითე: `bitcamp-ge/bitcamp-platform#5 task completed.`

წერილის ტექსტში მიუთითე ამ ტასკის ბმული.

ეს ტასკი დაიხურება ტრანზაქციის შესრულებისთანავე.

**Comment by otarza** [comment]
ტრანზაქცია შერსულებულია, დაიხურება დადასტურების მიღებისთანავე:

![942F025A-7BFD-466D-B67E-0279B018E061](https://user-images.githubusercontent.com/1330491/106723229-52425e80-6620-11eb-8eac-a9f017acdabf.jpeg)

**Comment by IliaNoz** [comment]
ვადასტურებ თახნის ჩარიცხვას.

**Comment by otarza** [comment]
@IliaNoz მადლობა, ვხურავ.
